server:
  port: ${PORT:8005}

spring:
  application:
    name: agent-service
  config:
    import: "optional:file:${AGENT_CONFIG_PATH:/etc/agent/agent.yml}"
  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          options:
            model: gemini-2.0-flash
            temperature: 0.2
            max-output-tokens: 1000
  cloud:
    function:
      definition: promptInput
    stream:
      bindings:
        promptInput-in-0:
          destination: prompt.exchange
          group: ${AGENT_TYPE:agent-default}
          contentType: application/json
        agentOutput:
          destination: response.exchange
          contentType: application/json
      rabbit:
        bindings:
          promptInput-in-0:
            consumer:
              exchangeType: fanout
          agentOutput:
            producer:
              exchangeType: fanout
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: guest
    password: guest


management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://tempo:4318/v1/traces

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    metadata-map:
      prometheus.port: ${server.port}

