server:
  port: ${PORT:8004}

spring:
  application:
    name: response-service
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
  cloud:
    function:
      definition: responseInput
    stream:
      bindings:
        responseInput-in-0:
          destination: response.exchange
          group: response-service
          contentType: application/json
        promptOutput:
          destination: prompt.exchange
          contentType: application/json
      rabbit:
        bindings:
          responseInput-in-0:
            consumer:
              exchangeType: fanout
          promptOutput:
            producer:
              exchangeType: fanout
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://tempo:4318/v1/traces

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    metadata-map:
      prometheus.port: ${server.port}

