global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'spring-boot-services'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'discovery-service:8761'
          - 'gateway-service:8060'
          - 'prompt-service:8003'
          - 'response-service:8004'
          - 'agent-java:8005'
          - 'agent-golang:8005'
          - 'agent-rust:8005'
