server:
  port: ${PORT:8003}

spring:
  application:
    name: prompt-service
  cloud:
    stream:
      bindings:
        promptOutput:
          destination: prompt.exchange
          contentType: application/json
      rabbit:
        bindings:
          promptOutput:
            producer:
              exchangeType: fanout
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    metadata-map:
      prometheus.port: ${server.port}

